### ISSUE TITLE
import knn graph?

### ISSUE THREAD

**Issue by bjstewart1** [YosefLab/Hotspot#10]
Would it be useful to have a function to import and use the neighbor graph computed in scanpy (fast for big datasests) 
the function `hs.create_knn_graph` seems a bit slow on very big datasets, and if the nn graph is already being computed for other analyses in scanpy makes sense to reuse this?

Genuinely very useful tool :)

**Comment by deto** [comment]
I agree - it definitely would make sense!  It's been on my todo-list for a while, but keeps getting pushed back by other life/work stuff.  What makes it non-trivial is that I wrote the functions assuming the graph could be represented by a Cells x Neighbors matrix (one for identity, one for weights), and scanpy uses the (more general) sparse Cells x Cells structure.  You can't just coerce the Cells x Cells structure into a Cells x Neighbors trivially because in the more general form, a cell could have a variable number of neighbors.  The math doesn't require this, though, so I would need to just rewrite the inner functions to take in, and operate on, a list of edges instead.

**Comment by bjstewart1** [comment]
makes sense, would really enhance the tool I think

**Comment by adamgayoso** [comment]
Can you give sklearn nearest neighbors the precomputed scanpy cells x cells matrix?

**Comment by deto** [comment]
It's really just an issue of data structure conversion

Scanpys neighbor graph can have an arbitrary number of neighbors per cell.
So you can't directly coerce it into an NxK array where every cell has K
neighbors and that's what the functions expect.

Though a quick hack might be to just put it into an NxK_max array and for
all cells with less than K_max neighbors, pad them with placeholder weight
zero connections.  I think the resulting calculation would work out, though
it would be less efficient computationally.

**Comment by adamgayoso** [comment]
Seems like you can do that [here](https://pynndescent.readthedocs.io/en/latest/how_to_use_pynndescent.html#Nearest-neighbors-of-the-training-set) with pynndescent (umap approx neighbors)
