### ISSUE TITLE
include self edges in gene-gene correlations?

### ISSUE THREAD

**Issue by phbradley** [YosefLab/Hotspot#6]
Hi there,
Thanks for this really interesting work! I admit that this is not a traditional "issue" but I was curious: I think I understand why self-edges should be excluded from the autocorrelation but I wonder whether it might make sense to include self-edges in the neighbor graph when computing gene-gene pairwise correlations. This would correspond to adding in the traditional correlation, I guess. I have not browsed deeply the code nor have I completely read the preprint, so my apologies if this is already addressed either place.
Again, congrats on a neat package!
Take care,
Phil
PS. Feel free to close this "issue" if there is a better forum for such a query...

**Comment by deto** [comment]
The idea here was that I wanted to make sure that correlations between genes were conditioned on the neighborhood graph entirely, such that if random connections between cells were formed, you would get the null distribution.  Adding in the traditional correlation would introduce terms that are not dependent on the graph (the within-cell correlations) and so it wouldn't be possible to determine if the association between two genes was due to, e.g., the spatial positions of the cells or just cell-intrinsic correlations (possibly due to technical or confounding factors).

This is for the multi-modal sense, though.  In the case where the neighborhood graph is also developed based on transcriptional data, I'm not sure it's really necessary to exclude the self edge, and I'm considering adding that as an option when computing the neighborhood graph.

**Comment by phbradley** [comment]
Thanks for your reply, that makes total sense. I did have one other tiny question: the formula for the variance of H-hat on the top of page 11 in the preprint, does that assume that the weights are asymmetric, in the sense that if w_ij != 0 then w_ji = 0 (in the case where i is a neighbor of j and j is also a neighbor of i)? I was trying to get it to work out for a graph where the weights are all 1 and there could be i->j and j->i neighbor relations and it seems like there is a term missing. No hurry on this, just for my own benefit since I was thinking of coding up a simplified version in some software I am working on. Again, very cool ideas!

**Comment by deto** [comment]
Hey phbradley, sorry for not getting back to you on this (I was just looking at old issues and realized this was still here).  In the derivations, I assume that it's an undirected graph - so for a pair of cells, there is just one weight.
